# Generated by Django 4.2.11 on 2026-04-26 10:59

import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('matters', '0001_initial'),
        ('firms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatterLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('opened_on', models.DateTimeField(auto_now_add=True)),
                ('closed_on', models.DateTimeField(blank=True, null=True)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledgers', to='matters.matter')),
            ],
            options={
                'verbose_name': 'Matter Ledger',
                'verbose_name_plural': 'Matter Ledgers',
            },
        ),
        migrations.CreateModel(
            name='PowerMoneyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_instrument', models.FileField(upload_to='trust/power/')),
                ('donor', models.CharField(max_length=255)),
                ('donee', models.CharField(max_length=255)),
                ('amount_held', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Power Money Entry',
                'verbose_name_plural': 'Power Money Entries',
            },
        ),
        migrations.CreateModel(
            name='TransitMoneyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_on', models.DateField()),
                ('payor', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('to_be_paid_to', models.CharField(max_length=255)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Transit Money Entry',
                'verbose_name_plural': 'Transit Money Entries',
            },
        ),
        migrations.CreateModel(
            name='TrustTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('receipt', 'Receipt'), ('payment', 'Payment'), ('journal_in', 'Journal In'), ('journal_out', 'Journal Out'), ('transfer_to_office', 'Transfer to Office'), ('reversal', 'Reversal')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date_received_or_paid', models.DateField()),
                ('date_banked', models.DateField(blank=True, null=True)),
                ('description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reversed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trust_transactions', to=settings.AUTH_USER_MODEL)),
                ('matter_ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='trust.matterledger')),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='trust.trusttransaction')),
            ],
            options={
                'verbose_name': 'Trust Transaction',
                'verbose_name_plural': 'Trust Transactions',
            },
        ),
        migrations.CreateModel(
            name='WrittenDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_text', models.TextField()),
                ('signed_on', models.DateField()),
                ('document', models.FileField(upload_to='trust/directions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='written_directions', to='clients.client')),
                ('linked_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='written_directions', to='trust.trusttransaction')),
                ('matter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='written_directions', to='matters.matter')),
            ],
            options={
                'verbose_name': 'Written Direction',
                'verbose_name_plural': 'Written Directions',
            },
        ),
        migrations.CreateModel(
            name='TrustJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.CharField(max_length=500)),
                ('written_authority', models.FileField(upload_to='trust/authorities/')),
                ('authority_date', models.DateField()),
                ('authority_signed_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trust_journals', to=settings.AUTH_USER_MODEL)),
                ('from_ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journals_out', to='trust.matterledger')),
                ('journal_in_txn', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_as_in', to='trust.trusttransaction')),
                ('journal_out_txn', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_as_out', to='trust.trusttransaction')),
                ('to_ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journals_in', to='trust.matterledger')),
            ],
            options={
                'verbose_name': 'Trust Journal',
                'verbose_name_plural': 'Trust Journals',
            },
        ),
        migrations.CreateModel(
            name='TrustAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bank', models.CharField(max_length=255)),
                ('bsb', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^\\d{3}-\\d{3}$', 'BSB must be in format 000-000')])),
                ('account_number', models.CharField(max_length=20)),
                ('is_general', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('next_receipt_number', models.PositiveIntegerField(default=1)),
                ('next_payment_number', models.PositiveIntegerField(default=1)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trust_accounts', to='firms.firm')),
            ],
            options={
                'verbose_name': 'Trust Account',
                'verbose_name_plural': 'Trust Accounts',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.PositiveIntegerField()),
                ('payee_name', models.CharField(max_length=255)),
                ('payee_bsb', models.CharField(blank=True, max_length=7)),
                ('payee_account', models.CharField(blank=True, max_length=20)),
                ('payment_method', models.CharField(choices=[('cheque', 'Cheque'), ('eft', 'EFT')], max_length=10)),
                ('cheque_number', models.CharField(blank=True, max_length=50)),
                ('purpose', models.CharField(max_length=500)),
                ('authorised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trust_payments_authorised', to=settings.AUTH_USER_MODEL)),
                ('second_authoriser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trust_payments_second_authorised', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='trust.trusttransaction')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.AddField(
            model_name='matterledger',
            name='trust_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledgers', to='trust.trustaccount'),
        ),
        migrations.CreateModel(
            name='Irregularity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discovered_on', models.DateField(default=datetime.date.today)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reported_to_law_society_on', models.DateField(blank=True, null=True)),
                ('report_document', models.FileField(blank=True, null=True, upload_to='trust/irregularities/')),
                ('resolution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trust_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='irregularities', to='trust.trustaccount')),
            ],
            options={
                'verbose_name': 'Irregularity',
                'verbose_name_plural': 'Irregularities',
            },
        ),
        migrations.CreateModel(
            name='ControlledMoneyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=255)),
                ('bsb', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^\\d{3}-\\d{3}$', 'BSB must be in format 000-000')])),
                ('account_number', models.CharField(max_length=20)),
                ('client_instruction_document', models.FileField(upload_to='controlled_money/instructions/')),
                ('interest_disposition', models.TextField()),
                ('opened_on', models.DateField(default=datetime.date.today)),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controlled_money_accounts', to='clients.client')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controlled_money_accounts', to='firms.firm')),
                ('matter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controlled_money_accounts', to='matters.matter')),
            ],
            options={
                'verbose_name': 'Controlled Money Account',
                'verbose_name_plural': 'Controlled Money Accounts',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.PositiveIntegerField()),
                ('payor_name', models.CharField(max_length=255)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('eft', 'EFT'), ('direct_deposit', 'Direct Deposit')], max_length=20)),
                ('cheque_number', models.CharField(blank=True, max_length=50)),
                ('purpose', models.CharField(max_length=500)),
                ('late_banking', models.BooleanField(default=False)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='trust.trusttransaction')),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'unique_together': {('receipt_number', 'transaction')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_end', models.DateField()),
                ('cash_book_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ledger_total_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bank_statement_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unpresented_cheques_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('outstanding_deposits_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reconciled_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('signed_on', models.DateTimeField(blank=True, null=True)),
                ('bank_statement_pdf', models.FileField(blank=True, null=True, upload_to='trust/recons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations_signed', to=settings.AUTH_USER_MODEL)),
                ('trust_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='trust.trustaccount')),
            ],
            options={
                'verbose_name': 'Monthly Reconciliation',
                'verbose_name_plural': 'Monthly Reconciliations',
                'unique_together': {('trust_account', 'period_end')},
            },
        ),
        migrations.AddConstraint(
            model_name='matterledger',
            constraint=models.CheckConstraint(check=models.Q(('balance__gte', 0)), name='matter_ledger_balance_non_negative'),
        ),
        migrations.AlterUniqueTogether(
            name='matterledger',
            unique_together={('matter', 'trust_account')},
        ),
    ]
