# Generated by Django 4.2.11 on 2026-06-12 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trust", "0003_simplified_phase_a_monthly_close"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="trustaccountingperiod",
            new_name="trust_trust_trust_a_333234_idx",
            old_name="trust_trust_trust_a_7e3252_idx",
        ),
        migrations.RenameIndex(
            model_name="trustaccountingperiod",
            new_name="trust_trust_trust_a_eebe41_idx",
            old_name="trust_trust_trust_a_35b8b4_idx",
        ),
        migrations.RenameIndex(
            model_name="trustmonthlyrecord",
            new_name="trust_trust_trust_a_acefd1_idx",
            old_name="trust_trust_trust_a_8acced_idx",
        ),
        migrations.RenameIndex(
            model_name="trustmonthlyrecord",
            new_name="trust_trust_trust_a_7a4575_idx",
            old_name="trust_trust_trust_a_8764ca_idx",
        ),
    ]
