# Generated by Codex on 2026-06-16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("trust", "0004_rename_trust_trust_trust_a_7e3252_idx_trust_trust_trust_a_333234_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trusttransaction",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
