# Generated by Codex for Rule 48 ledger reconciliation label clarification.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0005_trusttransaction_created_at_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trustmonthlyrecord',
            name='record_type',
            field=models.CharField(
                choices=[
                    ('receipts_cash_book', 'Receipts Cash Book'),
                    ('payments_cash_book', 'Payments Cash Book'),
                    ('trust_transfer_journal', 'Trust Transfer Journal'),
                    ('trial_balance', 'Ledger Reconciliation / Trial Balance'),
                    ('reconciliation_statement', 'Reconciliation Statement'),
                ],
                max_length=40,
            ),
        ),
    ]
