# Generated by Codex for Section 5 trust-record completeness foundation.

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('trust', '0006_update_trial_balance_record_label'),
        ('firms', '0001_initial'),
        ('matters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField('trustaccount', 'next_controlled_money_receipt_number', models.PositiveIntegerField(default=1)),
        migrations.AddField('controlledmoneyaccount', 'account_name', models.CharField(blank=True, default='', max_length=255)),
        migrations.AlterField('controlledmoneyaccount', 'client_instruction_document', models.FileField(blank=True, null=True, upload_to='controlled_money/instructions/')),
        migrations.AlterField('controlledmoneyaccount', 'interest_disposition', models.TextField(blank=True, default='')),
        migrations.AddField('controlledmoneyaccount', 'purpose', models.TextField(blank=True, default='')),
        migrations.AddField('controlledmoneyaccount', 'person_on_behalf', models.CharField(blank=True, default='', max_length=255)),
        migrations.AddField('controlledmoneyaccount', 'person_address', models.TextField(blank=True, default='')),
        migrations.AddField('controlledmoneyaccount', 'matter_reference', models.CharField(blank=True, default='', max_length=100)),
        migrations.AddField('controlledmoneyaccount', 'matter_description', models.CharField(blank=True, default='', max_length=500)),
        migrations.AddField('controlledmoneyaccount', 'current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
        migrations.AddField('controlledmoneyaccount', 'is_active', models.BooleanField(default=True)),
        migrations.CreateModel(
            name='ControlledMoneyReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.PositiveIntegerField()),
                ('date_made_out', models.DateField(default=django.utils.timezone.localdate)),
                ('date_money_received', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('eft', 'EFT'), ('direct_deposit', 'Direct Deposit')], max_length=20)),
                ('person_from_whom_received', models.CharField(max_length=255)),
                ('person_on_behalf', models.CharField(max_length=255)),
                ('matter_description', models.CharField(max_length=500)),
                ('matter_reference', models.CharField(blank=True, max_length=100)),
                ('reason', models.CharField(max_length=500)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('not_delivered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('controlled_money_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='trust.controlledmoneyaccount')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controlled_money_receipts', to='firms.firm')),
                ('made_out_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controlled_money_receipts_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['receipt_number']},
        ),
        migrations.CreateModel(
            name='ControlledMoneyWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transaction_number', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('withdrawal_method', models.CharField(choices=[('cheque', 'Cheque'), ('eft', 'EFT')], max_length=10)),
                ('payee', models.CharField(blank=True, max_length=255)),
                ('destination_account_name', models.CharField(blank=True, max_length=255)),
                ('destination_account_number', models.CharField(blank=True, max_length=20)),
                ('destination_bsb', models.CharField(blank=True, max_length=7)),
                ('person_receiving_benefit', models.CharField(blank=True, max_length=255)),
                ('person_on_behalf', models.CharField(max_length=255)),
                ('matter_reference', models.CharField(blank=True, max_length=100)),
                ('reason', models.CharField(max_length=500)),
                ('authorised_by', models.CharField(max_length=500)),
                ('supporting_authority', models.FileField(blank=True, null=True, upload_to='controlled_money/authorities/')),
                ('included_in_monthly_statement', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('controlled_money_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='trust.controlledmoneyaccount')),
            ],
        ),
        migrations.CreateModel(
            name='ControlledMoneySupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('adi_statement', 'ADI statement'), ('interest_notification', 'Interest notification'), ('authority', 'Authority/direction'), ('other', 'Other')], max_length=30)),
                ('document', models.FileField(upload_to='controlled_money/supporting/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('controlled_money_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supporting_documents', to='trust.controlledmoneyaccount')),
            ],
        ),
        migrations.CreateModel(
            name='ControlledMoneyMonthlyStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_end', models.DateField()),
                ('prepared_on', models.DateField(default=django.utils.timezone.localdate)),
                ('reviewed_on', models.DateField(blank=True, null=True)),
                ('reviewer_role_confirmation', models.CharField(blank=True, max_length=255)),
                ('review_note', models.TextField(blank=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='controlled_money/monthly-statements/')),
                ('sha256_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controlled_money_monthly_statements', to='firms.firm')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controlled_money_statements_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint('controlledmoneyreceipt', models.UniqueConstraint(fields=('firm', 'receipt_number'), name='unique_cma_receipt_number_per_firm')),
        migrations.AddConstraint('controlledmoneymonthlystatement', models.UniqueConstraint(fields=('firm', 'period_end'), name='unique_cma_monthly_statement_per_firm')),
    ]
