# Generated by Django 4.2.11 on 2026-06-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trust", "0007_section5_trust_record_completeness"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="controlledmoneywithdrawal",
            constraint=models.UniqueConstraint(
                fields=("controlled_money_account", "transaction_number"),
                name="unique_cma_withdrawal_transaction_number_per_account",
            ),
        ),
    ]
