# Generated by Django 4.2.11 on 2026-06-17 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "trust",
            "0008_controlledmoneywithdrawal_unique_cma_withdrawal_transaction_number_per_account",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="trustaccount",
            name="closed_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trustaccount",
            name="law_society_closure_notice_sent_on",
            field=models.DateField(
                blank=True,
                help_text="Optional admin record: Rule 50(3) notice sent within 14 days of closure.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trustaccount",
            name="law_society_opening_notice_sent_on",
            field=models.DateField(
                blank=True,
                help_text="Optional admin record: Rule 50(1) notice sent within 14 days of opening.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trustaccount",
            name="opened_on",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
