# Generated by Django 4.2.11 on 2026-06-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trust", "0009_trustaccount_closed_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("cheque", "Cheque"),
                    ("eft", "EFT"),
                    ("direct_deposit", "Direct Deposit"),
                    ("credit_card", "Credit Card"),
                ],
                max_length=20,
            ),
        ),
    ]
