# Generated by Django 4.2.11 on 2026-06-18 06:06

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trust", "0010_alter_receipt_payment_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReconciliationBankLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_date", models.DateField()),
                (
                    "line_type",
                    models.CharField(
                        choices=[
                            ("credit", "Credit in authorised ADI statement"),
                            ("debit", "Debit in authorised ADI statement"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("matched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciliation_bank_lines_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "matched_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciliation_bank_lines_matched",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "matched_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authorised_adi_matches",
                        to="trust.trusttransaction",
                    ),
                ),
                (
                    "reconciliation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_lines",
                        to="trust.monthlyreconciliation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Authorised ADI Statement Line",
                "verbose_name_plural": "Authorised ADI Statement Lines",
                "ordering": ["line_date", "id"],
                "indexes": [
                    models.Index(
                        fields=["reconciliation", "line_type"],
                        name="trust_recon_reconci_79d64f_idx",
                    ),
                    models.Index(
                        fields=["reconciliation", "matched_transaction"],
                        name="trust_recon_reconci_fd2576_idx",
                    ),
                    models.Index(
                        fields=["line_date"], name="trust_recon_line_da_e83442_idx"
                    ),
                ],
            },
        ),
    ]
