# Generated by Django 4.2.11 on 2026-06-18 07:24

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trust", "0011_reconciliation_bank_matching"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlyreconciliation",
            name="credits_not_in_cash_book_total",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="monthlyreconciliation",
            name="debits_not_in_cash_book_total",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="monthlyreconciliation",
            name="other_payments_not_in_adi_total",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="reconciliationbankline",
            name="adjustment_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Unclassified / requires review"),
                    ("matched_to_cash_book", "Matched to cash book"),
                    (
                        "receipt_to_issue_next_month",
                        "Direct deposit / receipt to be issued next month",
                    ),
                    ("unidentified_deposit", "Unidentified deposit"),
                    (
                        "adi_error_bank_to_reverse",
                        "Authorised ADI error - bank to reverse",
                    ),
                    (
                        "interest_credited_in_error",
                        "Interest credited in error - bank to reverse",
                    ),
                    (
                        "bank_charge_debited_in_error",
                        "Bank charge debited in error - bank to reverse",
                    ),
                    (
                        "bank_debit_not_in_cash_book",
                        "Bank debit not in cash book - investigate/correct",
                    ),
                    ("unpresented_cheque", "Unpresented cheque"),
                    (
                        "other_payment_not_in_adi",
                        "Other payment in cash book not in authorised ADI statement",
                    ),
                    ("other_adjustment", "Other reconciliation adjustment"),
                ],
                default="",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="reconciliationbankline",
            name="carry_forward_until_cleared",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reconciliationbankline",
            name="cleared_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reconciliationbankline",
            name="cleared_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reconciliation_bank_lines_cleared",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reconciliationbankline",
            name="cleared_by_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clears_reconciliation_adjustments",
                to="trust.trusttransaction",
            ),
        ),
        migrations.AddField(
            model_name="reconciliationbankline",
            name="cleared_in_reconciliation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cleared_bank_line_adjustments",
                to="trust.monthlyreconciliation",
            ),
        ),
        migrations.AddField(
            model_name="reconciliationbankline",
            name="cleared_notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
