# Generated by Django 4.2.11 on 2026-06-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trust", "0012_reconciliation_adjustment_carry_forward"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="payment_reference_override",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
