# Generated by Django 4.2.11 on 2026-06-22 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trust", "0013_payment_reference_override"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepositRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deposit_number", models.PositiveIntegerField()),
                (
                    "deposit_type",
                    models.CharField(
                        choices=[
                            ("cash", "Cash Deposit Record"),
                            ("cheque", "Cheque Deposit Record"),
                        ],
                        max_length=10,
                    ),
                ),
                ("deposit_date", models.DateField()),
                ("prepared_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "prepared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deposit_records_prepared",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trust_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deposit_records",
                        to="trust.trustaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deposit Record",
                "verbose_name_plural": "Deposit Records",
                "ordering": ["-deposit_date", "-deposit_number"],
            },
        ),
        migrations.AddField(
            model_name="receipt",
            name="deposit_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receipts",
                to="trust.depositrecord",
            ),
        ),
        migrations.AddIndex(
            model_name="depositrecord",
            index=models.Index(
                fields=["trust_account", "deposit_type"],
                name="trust_depos_trust_a_f4de78_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="depositrecord",
            index=models.Index(
                fields=["deposit_date"], name="trust_depos_deposit_a6cb85_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="depositrecord",
            unique_together={("trust_account", "deposit_number")},
        ),
    ]
