# Generated by Django 4.2.11 on 2026-06-22 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trust", "0014_deposit_records"),
    ]

    operations = []
