# Generated by Django 4.2.11 on 2026-06-22 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trust", "0015_authorised_signatories"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorisedSignatory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True, default="")),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("principal", "Principal"),
                            ("solicitor", "Solicitor / legal practitioner associate"),
                            ("employee", "Employee / associate"),
                            ("consultant", "Consultant"),
                            ("other", "Other authorised associate"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "practising_certificate_number",
                    models.CharField(blank=True, max_length=80),
                ),
                ("authorised_trust_cheques", models.BooleanField(default=False)),
                ("authorised_trust_efts", models.BooleanField(default=False)),
                ("authorised_controlled_money", models.BooleanField(default=False)),
                ("authorised_from", models.DateField()),
                ("authorised_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trust_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorised_signatories",
                        to="trust.trustaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Authorised Signatory",
                "verbose_name_plural": "Authorised Signatories",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["trust_account", "is_active"],
                        name="trust_autho_trust_a_4e4534_idx",
                    ),
                    models.Index(
                        fields=["authorised_from"],
                        name="trust_autho_authori_cff807_idx",
                    ),
                ],
            },
        ),
    ]
