# Generated by Django 4.2.11 on 2026-06-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trust", "0016_authorised_signatories"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorisedsignatory",
            name="last_reviewed_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="authorisedsignatory",
            name="next_review_due_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="authorisedsignatory",
            name="review_notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
