# Generated by Django 4.2.11 on 2026-06-24 22:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0001_initial"),
        ("clients", "0001_initial"),
        ("trust", "0017_authorisedsignatory_last_reviewed_on_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transitmoneyentry",
            options={
                "ordering": ["-received_on", "-created_at"],
                "verbose_name": "Transit Money Entry",
                "verbose_name_plural": "Transit Money Entries",
            },
        ),
        migrations.AddField(
            model_name="transitmoneyentry",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transit_money_entries",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="transitmoneyentry",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transitmoneyentry",
            name="instructions_document",
            field=models.FileField(
                blank=True, null=True, upload_to="trust/transit-money/instructions/"
            ),
        ),
        migrations.AddField(
            model_name="transitmoneyentry",
            name="matter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transit_money_entries",
                to="matters.matter",
            ),
        ),
        migrations.AddField(
            model_name="transitmoneyentry",
            name="purpose",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="transitmoneyentry",
            name="supporting_document",
            field=models.FileField(
                blank=True, null=True, upload_to="trust/transit-money/supporting/"
            ),
        ),
    ]
