# Generated by Django 4.2.11 on 2026-06-24 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trust", "0018_alter_transitmoneyentry_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transitmoneyentry",
            options={
                "ordering": ["-received_on"],
                "verbose_name": "Transit Money Entry",
                "verbose_name_plural": "Transit Money Entries",
            },
        ),
        migrations.RemoveField(
            model_name="authorisedsignatory",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="controlledmoneymonthlystatement",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="controlledmoneyreceipt",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="controlledmoneywithdrawal",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="irregularity",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="monthlyreconciliation",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="reconciliationbankline",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="transitmoneyentry",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="trustaccountingperiod",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="trustjournal",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="writtendirection",
            name="created_at",
        ),
    ]
