# Generated by Django 4.2.11 on 2026-06-24 22:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("trust", "0019_alter_transitmoneyentry_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorisedsignatory",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="controlledmoneymonthlystatement",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="controlledmoneyreceipt",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="controlledmoneywithdrawal",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="monthlyreconciliation",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="reconciliationbankline",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="trustaccountingperiod",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="writtendirection",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
