# Generated by Django 4.2.11 on 2026-06-25 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        ("matters", "0001_initial"),
        ("trust", "0020_authorisedsignatory_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="powermoneyentry",
            options={
                "ordering": ["-power_date", "donor", "deceased_name"],
                "verbose_name": "Power / Estate Register Entry",
                "verbose_name_plural": "Powers & Estates Register",
            },
        ),
        migrations.AddField(
            model_name="powermoneyentry",
            name="authority_document",
            field=models.FileField(
                blank=True, null=True, upload_to="trust/power/authorities/"
            ),
        ),
        migrations.AddField(
            model_name="powermoneyentry",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="power_money_entries",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="powermoneyentry",
            name="date_of_death",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="powermoneyentry",
            name="deceased_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="powermoneyentry",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="powermoneyentry",
            name="donor_address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="powermoneyentry",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("power", "Power of attorney / authority"),
                    ("estate", "Estate"),
                    ("guardianship", "Guardianship order"),
                    ("probate", "Probate / administration"),
                    ("other", "Other"),
                ],
                default="power",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="powermoneyentry",
            name="matter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="power_money_entries",
                to="matters.matter",
            ),
        ),
        migrations.AddField(
            model_name="powermoneyentry",
            name="matter_reference",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="powermoneyentry",
            name="power_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="powermoneyentry",
            name="responsible_solicitor",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="powermoneyentry",
            name="amount_held",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="powermoneyentry",
            name="donee",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="powermoneyentry",
            name="donor",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="powermoneyentry",
            name="power_instrument",
            field=models.FileField(blank=True, null=True, upload_to="trust/power/"),
        ),
        migrations.CreateModel(
            name="PowerMoneyDealing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dealing_date", models.DateField()),
                ("description", models.TextField()),
                (
                    "deposit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "withdrawal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "payee_or_source",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "supporting_document",
                    models.FileField(
                        blank=True, null=True, upload_to="trust/power/dealings/"
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "power_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dealings",
                        to="trust.powermoneyentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Power / Estate Dealing",
                "verbose_name_plural": "Power / Estate Dealings",
                "ordering": ["dealing_date", "id"],
            },
        ),
    ]
