# Generated by Django 4.2.11 on 2026-06-25 07:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        ("matters", "0001_initial"),
        ("trust", "0021_alter_powermoneyentry_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrustInvestment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person_on_behalf", models.CharField(max_length=255)),
                ("person_address", models.TextField(blank=True, default="")),
                (
                    "investment_held_name",
                    models.CharField(
                        help_text="Name in which investment is held", max_length=255
                    ),
                ),
                (
                    "institution",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "investment_type",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("investment_particulars", models.TextField(blank=True, default="")),
                (
                    "amount_invested",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("date_invested", models.DateField()),
                (
                    "source_of_investment",
                    models.CharField(
                        choices=[
                            ("general_trust", "General Trust Account"),
                            ("controlled_money", "Controlled Money Account"),
                            ("transit_money", "Transit Money"),
                            ("power_money", "Power Money"),
                            ("other", "Other"),
                        ],
                        default="general_trust",
                        max_length=30,
                    ),
                ),
                (
                    "source_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "trust_ledger_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "written_direction_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("written_direction_date", models.DateField(blank=True, null=True)),
                (
                    "cheque_or_eft_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("investment_terms", models.TextField(blank=True, default="")),
                (
                    "document_identifier",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "evidence_document",
                    models.FileField(
                        blank=True, null=True, upload_to="trust/investments/evidence/"
                    ),
                ),
                (
                    "written_direction_document",
                    models.FileField(
                        blank=True, null=True, upload_to="trust/investments/directions/"
                    ),
                ),
                ("interest_details", models.TextField(blank=True, default="")),
                (
                    "maturity_repayment_details",
                    models.TextField(blank=True, default=""),
                ),
                ("repaid_on", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trust_investments",
                        to="clients.client",
                    ),
                ),
                (
                    "matter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trust_investments",
                        to="matters.matter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trust Investment",
                "verbose_name_plural": "Trust Investments",
                "ordering": ["-date_invested", "person_on_behalf"],
            },
        ),
    ]
