# Generated by Django 4.2.11 on 2026-06-25 11:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("trust", "0022_trustinvestment"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatutoryDepositRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applicable_period_end", models.DateField()),
                (
                    "statutory_deposit_adi",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "statutory_deposit_account_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("calculated_on", models.DateField(blank=True, null=True)),
                (
                    "required_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "amount_currently_held",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "adjustment_required",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("adjustment_due_date", models.DateField(blank=True, null=True)),
                ("adjustment_made_on", models.DateField(blank=True, null=True)),
                ("calculation_notes", models.TextField(blank=True, default="")),
                (
                    "supporting_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="trust/statutory-deposits/supporting/",
                    ),
                ),
                (
                    "law_society_determination_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="trust/statutory-deposits/law-society/",
                    ),
                ),
                ("next_review_due_on", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "trust_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="statutory_deposit_records",
                        to="trust.trustaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statutory Deposit Record",
                "verbose_name_plural": "Statutory Deposit Records",
                "ordering": ["-applicable_period_end", "trust_account"],
            },
        ),
    ]
