# Generated by Django 4.2.11 on 2026-06-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trust", "0023_statutorydepositrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="trustinvestment",
            name="maturity_due_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]
