# Generated by Django 4.2.11 on 2026-06-28 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("firms", "0001_initial"),
        ("matters", "0003_alter_matter_date_instructions_received"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trust", "0024_trustinvestment_maturity_due_on"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceReviewLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alert_key", models.CharField(blank=True, default="", max_length=255)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("Action Required", "Action Required"),
                            ("Review Required", "Review Required"),
                            ("Reminder", "Reminder"),
                            ("Information", "Information"),
                        ],
                        default="Review Required",
                        max_length=30,
                    ),
                ),
                ("category", models.CharField(max_length=120)),
                ("title", models.CharField(max_length=255)),
                (
                    "source_url",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("reviewed", "Reviewed"),
                            ("resolved", "Resolved"),
                            ("not_applicable", "Not applicable"),
                            ("follow_up_required", "Follow-up required"),
                        ],
                        default="reviewed",
                        max_length=30,
                    ),
                ),
                ("review_note", models.TextField(blank=True, default="")),
                ("reviewed_on", models.DateTimeField(blank=True, null=True)),
                ("next_review_on", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compliance_review_logs",
                        to="firms.firm",
                    ),
                ),
                (
                    "matter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compliance_review_logs",
                        to="matters.matter",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compliance_reviews_completed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Compliance Review Log",
                "verbose_name_plural": "Compliance Review Logs",
                "ordering": ["-reviewed_on", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["firm", "status"], name="trust_compl_firm_id_389bdb_idx"
                    ),
                    models.Index(
                        fields=["firm", "category"],
                        name="trust_compl_firm_id_f23b87_idx",
                    ),
                    models.Index(
                        fields=["firm", "next_review_on"],
                        name="trust_compl_firm_id_e42e4d_idx",
                    ),
                    models.Index(
                        fields=["alert_key"], name="trust_compl_alert_k_6523b7_idx"
                    ),
                ],
            },
        ),
    ]
