# Generated by Django 4.2.11 on 2026-06-28 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("firms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trust", "0025_compliancereviewlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section19ComplianceReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_period_start", models.DateField()),
                ("review_period_end", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("requires_action", "Requires action"),
                        ],
                        default="in_progress",
                        max_length=30,
                    ),
                ),
                ("debit_balances_reviewed", models.BooleanField(default=False)),
                ("debit_balances_notes", models.TextField(blank=True, default="")),
                ("old_balances_reviewed", models.BooleanField(default=False)),
                ("old_balances_notes", models.TextField(blank=True, default="")),
                ("reconciliations_reviewed", models.BooleanField(default=False)),
                ("reconciliations_notes", models.TextField(blank=True, default="")),
                ("unidentified_money_reviewed", models.BooleanField(default=False)),
                ("unidentified_money_notes", models.TextField(blank=True, default="")),
                ("controlled_money_reviewed", models.BooleanField(default=False)),
                ("controlled_money_notes", models.TextField(blank=True, default="")),
                ("written_directions_reviewed", models.BooleanField(default=False)),
                ("written_directions_notes", models.TextField(blank=True, default="")),
                ("trust_investments_reviewed", models.BooleanField(default=False)),
                ("trust_investments_notes", models.TextField(blank=True, default="")),
                ("statutory_deposits_reviewed", models.BooleanField(default=False)),
                ("statutory_deposits_notes", models.TextField(blank=True, default="")),
                ("source_documents_reviewed", models.BooleanField(default=False)),
                ("source_documents_notes", models.TextField(blank=True, default="")),
                ("corrective_action_summary", models.TextField(blank=True, default="")),
                ("reviewed_on", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="section19_reviews",
                        to="firms.firm",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="section19_reviews_completed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Section 19 Compliance Review",
                "verbose_name_plural": "Section 19 Compliance Reviews",
                "ordering": ["-review_period_end", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["firm", "status"], name="trust_secti_firm_id_4003cd_idx"
                    ),
                    models.Index(
                        fields=["firm", "review_period_end"],
                        name="trust_secti_firm_id_3e408c_idx",
                    ),
                ],
            },
        ),
    ]
