# Generated by Django 4.2.11 on 2026-06-28 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("firms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trust", "0026_section19compliancereview"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="section19compliancereview",
            options={
                "ordering": ["-review_period_end", "-created_at"],
                "verbose_name": "Periodic Trust Compliance Review",
                "verbose_name_plural": "Periodic Trust Compliance Reviews",
            },
        ),
        migrations.CreateModel(
            name="AnnualTrustComplianceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trust_year_start", models.DateField()),
                ("trust_year_end", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("requires_action", "Requires action"),
                        ],
                        default="in_progress",
                        max_length=30,
                    ),
                ),
                ("part_a_completed_on", models.DateField(blank=True, null=True)),
                ("part_b_required", models.BooleanField(default=False)),
                ("part_b_completed_on", models.DateField(blank=True, null=True)),
                ("external_examiner_required", models.BooleanField(default=False)),
                (
                    "external_examiner_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "external_examiner_report_lodged_on",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "bank_reconciliation_31_march",
                    models.FileField(
                        blank=True, null=True, upload_to="annual_trust_compliance/"
                    ),
                ),
                (
                    "trial_balance_31_march",
                    models.FileField(
                        blank=True, null=True, upload_to="annual_trust_compliance/"
                    ),
                ),
                (
                    "bank_statement_31_march",
                    models.FileField(
                        blank=True, null=True, upload_to="annual_trust_compliance/"
                    ),
                ),
                ("overdrawn_ledgers_reviewed", models.BooleanField(default=False)),
                (
                    "controlled_money_listing_reviewed",
                    models.BooleanField(default=False),
                ),
                (
                    "investment_money_listing_reviewed",
                    models.BooleanField(default=False),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("reviewed_on", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="annual_trust_compliance_records",
                        to="firms.firm",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="annual_trust_compliance_reviews_completed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Annual Trust Compliance Record",
                "verbose_name_plural": "Annual Trust Compliance Records",
                "ordering": ["-trust_year_end", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["firm", "trust_year_end"],
                        name="trust_annua_firm_id_a42b3e_idx",
                    ),
                    models.Index(
                        fields=["firm", "status"], name="trust_annua_firm_id_e49895_idx"
                    ),
                ],
            },
        ),
    ]
