# Generated by Django 4.2.11 on 2026-06-29 03:00

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("firms", "0001_initial"),
        ("trust", "0027_alter_section19compliancereview_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnclaimedMoneyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "date_identified",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("date_last_activity", models.DateField(blank=True, null=True)),
                (
                    "date_funds_became_potentially_unclaimed",
                    models.DateField(blank=True, null=True),
                ),
                ("last_client_contact_date", models.DateField(blank=True, null=True)),
                ("contact_attempts", models.TextField(blank=True)),
                ("review_notes", models.TextField(blank=True)),
                ("proposed_action", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("under_review", "Under review"),
                            ("client_contacted", "Client contacted"),
                            ("resolved", "Resolved"),
                            ("paid_out", "Paid out"),
                            (
                                "transferred",
                                "Transferred / dealt with under statutory process",
                            ),
                            ("closed", "Closed"),
                        ],
                        default="under_review",
                        max_length=30,
                    ),
                ),
                (
                    "supporting_document",
                    models.FileField(
                        blank=True, null=True, upload_to="trust/unclaimed-money/"
                    ),
                ),
                ("reviewed_on", models.DateField(blank=True, null=True)),
                ("resolved_on", models.DateField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unclaimed_money_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unclaimed_money_records",
                        to="firms.firm",
                    ),
                ),
                (
                    "matter_ledger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unclaimed_money_records",
                        to="trust.matterledger",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unclaimed_money_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trust_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unclaimed_money_records",
                        to="trust.trustaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unclaimed Money Record",
                "verbose_name_plural": "Unclaimed Money Records",
                "ordering": ["-date_identified", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["firm", "status"], name="trust_uncla_firm_id_2c985b_idx"
                    ),
                    models.Index(
                        fields=["trust_account", "status"],
                        name="trust_uncla_trust_a_fe5c66_idx",
                    ),
                    models.Index(
                        fields=["matter_ledger", "status"],
                        name="trust_uncla_matter__30256f_idx",
                    ),
                ],
            },
        ),
    ]
