# Generated by Django 4.2.11 on 2026-06-29 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trust", "0028_unclaimedmoneyrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorisedsignatory",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="authorised_signatory_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="authorisedsignatory",
            name="reviewed_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="statutorydepositrecord",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="statutory_deposit_record_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="statutorydepositrecord",
            name="reviewed_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]
