# Generated by Django 4.2.11 on 2026-06-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_firm"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_firm_approved",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user has been approved by the firm principal/admin to access this firm.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="mf2fa_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user has completed Matter Funds 2FA setup.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="mf2fa_required",
            field=models.BooleanField(
                default=True,
                help_text="Matter Funds 2FA requirement. Production users should not access Matter Funds without MF2FA.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("platform_admin", "Matter Funds platform admin"),
                    ("firm_admin", "Firm admin"),
                    ("principal", "Principal / trust compliance owner"),
                    ("authorised_trust_user", "Authorised trust user"),
                    ("accountant", "Accountant / bookkeeper"),
                    ("staff", "Staff"),
                    ("external_examiner", "External examiner / read-only reviewer"),
                    ("client", "Client"),
                    ("admin", "Legacy administrator"),
                    ("solicitor", "Legacy solicitor"),
                ],
                default="staff",
                max_length=30,
            ),
        ),
    ]
