from django.urls import path
from . import views

app_name = 'trust'
urlpatterns = [
    path('accounts/', views.TrustAccountListView.as_view(), name='account_list'),
    path('accounts/<int:pk>/', views.TrustAccountDetailView.as_view(), name='account_detail'),
    path('ledgers/<int:ledger_pk>/receipts/new/', views.ReceiptCreateView.as_view(), name='receipt_create'),
    path('receipts/<int:pk>/', views.ReceiptDetailView.as_view(), name='receipt_detail'),
    path('ledgers/<int:ledger_pk>/payments/new/', views.PaymentCreateView.as_view(), name='payment_create'),
    path('ledgers/<int:ledger_pk>/transfer-costs-to-office/new/', views.TransferCostsToOfficeCreateView.as_view(), name='transfer_costs_to_office_create'),
    path('journals/new/', views.TrustJournalCreateView.as_view(), name='journal_create'),
    path('transactions/<int:pk>/reverse/', views.ReverseTransactionView.as_view(), name='transaction_reverse'),
    path('periods/', views.AccountingPeriodListView.as_view(), name='period_list'),
    path('periods/<int:pk>/', views.AccountingPeriodDetailView.as_view(), name='period_detail'),
    path('periods/<int:pk>/lock/', views.AccountingPeriodLockView.as_view(), name='period_lock'),
    path('reconciliations/', views.ReconciliationListView.as_view(), name='reconciliation_list'),
    path('accounts/<int:pk>/reconciliations/new/', views.ReconciliationCreateView.as_view(), name='reconciliation_create'),
    path('reconciliations/<int:pk>/', views.ReconciliationDetailView.as_view(), name='reconciliation_detail'),
    path('reconciliations/<int:pk>/finalise/', views.ReconciliationFinaliseView.as_view(), name='reconciliation_finalise'),
    path('monthly-records/', views.MonthlyRecordListView.as_view(), name='monthly_record_list'),
    path('monthly-records/<int:pk>/', views.MonthlyRecordDetailView.as_view(), name='monthly_record_detail'),
    path('monthly-records/<int:pk>/download/', views.MonthlyRecordDownloadView.as_view(), name='monthly_record_download'),
    path('irregularities/', views.IrregularityListView.as_view(), name='irregularity_list'),
    path('irregularities/new/', views.IrregularityCreateView.as_view(), name='irregularity_create'),
    path('irregularities/<int:pk>/', views.IrregularityDetailView.as_view(), name='irregularity_detail'),
    path('reports/', views.ReportsLandingView.as_view(), name='reports'),
    path('accounts/<int:pk>/reports/receipts-journal/', views.ReceiptsJournalPDFView.as_view(), name='receipts_journal_pdf'),
    path('accounts/<int:pk>/reports/payments-journal/', views.PaymentsJournalPDFView.as_view(), name='payments_journal_pdf'),
    path('accounts/<int:pk>/reports/trust-transfer-journal/', views.TrustTransferJournalPDFView.as_view(), name='trust_transfer_journal_pdf'),
    path('accounts/<int:pk>/reports/trial-balance/', views.TrialBalancePDFView.as_view(), name='trial_balance_pdf'),
    path('accounts/<int:pk>/reports/examiner-pack/', views.ExaminerPackZipView.as_view(), name='examiner_pack'),
    path('ledgers/<int:pk>/reports/statement/', views.LedgerStatementPDFView.as_view(), name='ledger_statement_pdf'),
    path('reconciliations/<int:pk>/reports/pdf/', views.ReconciliationPDFView.as_view(), name='reconciliation_pdf'),
    path('receipts/<int:pk>/pdf/', views.ReceiptPDFView.as_view(), name='receipt_pdf'),
]
