from django.urls import path
from . import views

app_name = 'trust'
urlpatterns = [

    path('controlled-money/', views.ControlledMoneyAccountListView.as_view(), name='controlled_money_list'),
    path('controlled-money/accounts/new/', views.ControlledMoneyAccountCreateView.as_view(), name='controlled_money_create'),
    path('controlled-money/accounts/<int:pk>/', views.ControlledMoneyAccountDetailView.as_view(), name='controlled_money_detail'),
    path('controlled-money/receipts/new/', views.ControlledMoneyReceiptCreateView.as_view(), name='controlled_money_receipt_create'),
    path('controlled-money/receipts/<int:pk>/pdf/', views.ControlledMoneyReceiptPDFView.as_view(), name='controlled_money_receipt_pdf'),
    path('controlled-money/withdrawals/new/', views.ControlledMoneyWithdrawalCreateView.as_view(), name='controlled_money_withdrawal_create'),
    path('controlled-money/monthly-statements/', views.ControlledMoneyMonthlyStatementListView.as_view(), name='controlled_money_statements'),
    path('controlled-money/monthly-statements/<int:pk>/', views.ControlledMoneyMonthlyStatementDetailView.as_view(), name='controlled_money_statement_detail'),
    path('controlled-money/monthly-statements/<int:pk>/pdf/', views.ControlledMoneyMonthlyStatementPDFView.as_view(), name='controlled_money_statement_pdf'),
    path('accounts/', views.TrustAccountListView.as_view(), name='account_list'),
    path('accounts/<int:pk>/edit/', views.TrustAccountUpdateView.as_view(), name='account_update'),
    path('accounts/<int:pk>/', views.TrustAccountDetailView.as_view(), name='account_detail'),
    path('ledgers/<int:ledger_pk>/receipts/new/', views.ReceiptCreateView.as_view(), name='receipt_create'),
    path('receipts/<int:pk>/', views.ReceiptDetailView.as_view(), name='receipt_detail'),
    path('ledgers/<int:ledger_pk>/payments/new/', views.PaymentCreateView.as_view(), name='payment_create'),
    path('payments/<int:pk>/', views.PaymentDetailView.as_view(), name='payment_detail'),
    path('ledgers/<int:ledger_pk>/transfer-costs-to-office/new/', views.TransferCostsToOfficeCreateView.as_view(), name='transfer_costs_to_office_create'),
    path('journals/new/', views.TrustJournalCreateView.as_view(), name='journal_create'),
    path('journals/<int:pk>/', views.TrustJournalDetailView.as_view(), name='journal_detail'),
    path('journals/<int:pk>/pdf/', views.TrustJournalPDFView.as_view(), name='journal_pdf'),
    path('transactions/<int:pk>/reverse/', views.ReverseTransactionView.as_view(), name='transaction_reverse'),
    path('reversals/<int:pk>/', views.ReversalDetailView.as_view(), name='reversal_detail'),
    path('reversals/<int:pk>/pdf/', views.ReversalPDFView.as_view(), name='reversal_pdf'),
    path('periods/', views.AccountingPeriodListView.as_view(), name='period_list'),
    path('periods/<int:pk>/', views.AccountingPeriodDetailView.as_view(), name='period_detail'),
    path('periods/<int:pk>/lock/', views.AccountingPeriodLockView.as_view(), name='period_lock'),
    path('reconciliations/', views.ReconciliationListView.as_view(), name='reconciliation_list'),
    path('accounts/<int:pk>/reconciliations/new/', views.ReconciliationCreateView.as_view(), name='reconciliation_create'),
    path('reconciliations/<int:pk>/', views.ReconciliationDetailView.as_view(), name='reconciliation_detail'),
    path('reconciliations/<int:pk>/bank-statement/', views.ReconciliationBankStatementView.as_view(), name='reconciliation_bank_statement'),
    path('reconciliations/<int:pk>/finalise/', views.ReconciliationFinaliseView.as_view(), name='reconciliation_finalise'),
    path('monthly-records/', views.MonthlyRecordListView.as_view(), name='monthly_record_list'),
    path('monthly-records/<int:pk>/', views.MonthlyRecordDetailView.as_view(), name='monthly_record_detail'),
    path('monthly-records/<int:pk>/download/', views.MonthlyRecordDownloadView.as_view(), name='monthly_record_download'),
    path('irregularities/', views.IrregularityListView.as_view(), name='irregularity_list'),
    path('irregularities/new/', views.IrregularityCreateView.as_view(), name='irregularity_create'),
    path('irregularities/<int:pk>/', views.IrregularityDetailView.as_view(), name='irregularity_detail'),
    path('reports/', views.ReportsLandingView.as_view(), name='reports'),
    path('accounts/<int:pk>/reports/receipts-journal/', views.ReceiptsJournalPDFView.as_view(), name='receipts_journal_pdf'),
    path('accounts/<int:pk>/reports/payments-journal/', views.PaymentsJournalPDFView.as_view(), name='payments_journal_pdf'),
    path('accounts/<int:pk>/reports/trust-transfer-journal/', views.TrustTransferJournalPDFView.as_view(), name='trust_transfer_journal_pdf'),
    path('accounts/<int:pk>/reports/trust-cash-book-summary/', views.TrustCashBookSummaryPDFView.as_view(), name='trust_cash_book_summary_pdf'),
    path('accounts/<int:pk>/reports/trial-balance/', views.TrialBalancePDFView.as_view(), name='trial_balance_pdf'),
    path('accounts/<int:pk>/reports/examiner-pack/', views.ExaminerPackZipView.as_view(), name='examiner_pack'),
    path('accounts/<int:pk>/reports/trust-records-export-pack/', views.TrustRecordsExportPackZipView.as_view(), name='trust_records_export_pack'),
    path('ledgers/<int:pk>/reports/statement/', views.LedgerStatementPDFView.as_view(), name='ledger_statement_pdf'),
    path('ledgers/<int:pk>/reports/trust-account-statement/', views.TrustAccountStatementPDFView.as_view(), name='trust_account_statement_pdf'),
    path('reconciliations/<int:pk>/reports/pdf/', views.ReconciliationPDFView.as_view(), name='reconciliation_pdf'),
    path('receipts/<int:pk>/pdf/', views.ReceiptPDFView.as_view(), name='receipt_pdf'),
    path('payments/<int:pk>/pdf/', views.PaymentPDFView.as_view(), name='payment_pdf'),
]
