# Generated by Django 4.2.11 on 2026-04-26 10:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abn', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'ABN must be exactly 11 digits.')])),
                ('address', models.TextField()),
                ('is_sole_practitioner', models.BooleanField(default=False)),
                ('jurisdiction', models.CharField(choices=[('NSW', 'New South Wales'), ('VIC', 'Victoria'), ('QLD', 'Queensland'), ('WA', 'Western Australia'), ('SA', 'South Australia'), ('TAS', 'Tasmania'), ('ACT', 'Australian Capital Territory'), ('NT', 'Northern Territory')], default='NSW', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('principal_solicitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='principal_of', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Firm',
                'verbose_name_plural': 'Firms',
            },
        ),
    ]
