# Generated by Django 4.2.11 on 2026-06-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="firm",
            name="access_model",
            field=models.CharField(
                choices=[
                    ("saas", "Monthly SaaS subscription"),
                    ("perpetual", "Perpetual licence"),
                ],
                default="saas",
                help_text="Commercial access model for the law practice.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="firm",
            name="allow_self_registration",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, users may request access to this firm. Approval is still required.",
            ),
        ),
        migrations.AddField(
            model_name="firm",
            name="licence_issued_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="firm",
            name="licence_key",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="firm",
            name="licence_maintenance_expires_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="firm",
            name="mf2fa_mandatory",
            field=models.BooleanField(
                default=True,
                help_text="Firm-level requirement that all production users must use Matter Funds 2FA.",
            ),
        ),
        migrations.AddField(
            model_name="firm",
            name="read_only_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="firm",
            name="subscription_renews_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="firm",
            name="subscription_started_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="firm",
            name="subscription_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("trial", "Trial"),
                    ("grace", "Grace period"),
                    ("read_only", "Read-only compliance access"),
                    ("suspended", "Suspended"),
                ],
                default="trial",
                help_text="Current Matter Funds access status for this law practice.",
                max_length=20,
            ),
        ),
    ]
