# Generated by Django 4.2.11 on 2026-06-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matter",
            name="date_instructions_received",
            field=models.DateField(
                blank=True,
                help_text="Date instructions were first received for this matter.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="matter",
            name="regulated_property_location",
            field=models.CharField(
                blank=True,
                default="Principal Place of Practice",
                help_text="Location of regulated property for the matter.",
                max_length=255,
            ),
        ),
    ]
