# Generated by Django 4.2.11 on 2026-06-26 03:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0002_matter_date_instructions_received_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matter",
            name="date_instructions_received",
            field=models.DateField(
                default=datetime.date.today,
                help_text="Date instructions were first received for this matter.",
            ),
        ),
    ]
