# Generated by Django 4.2.11 on 2026-06-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0003_alter_matter_date_instructions_received"),
    ]

    operations = [
        migrations.AddField(
            model_name="matter",
            name="other_party",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Other party or counterparty for register-of-files-opened purposes.",
                max_length=255,
            ),
        ),
    ]
